######################################################################
# Automatically generated by qmake (2.01a) zo 6. mei 16:05:26 2007
######################################################################

TEMPLATE = vcapp
TARGET = qdigiplot
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cross.h qdigiplot.h scene.h view.h
SOURCES += cross.cpp main.cpp qdigiplot.cpp scene.cpp view.cpp
RESOURCES += resources.qrc
